export const GENERAL_PRACTICIONER = {
  naam: "Huisarts (Algemene Geneeskunde)",
  beschrijving:
    "Eerste aanspreekpunt voor algemene klachten, doorverwijzingen en preventieve zorg.",
  symptoms: [
    { name: "Koorts", urgency: 1 },
    { name: "Vermoeidheid", urgency: 1 },
    { name: "Algehele zwakte", urgency: 1 },
    { name: "Onverklaarbaar gewichtsverlies", urgency: 2 },
    { name: "Lichte pijn", urgency: 1 },
    { name: "Hoest", urgency: 1 },
    { name: "Verkoudheid", urgency: 1 },
    { name: "Griepachtige klachten", urgency: 1 },
    { name: "Kleine infecties", urgency: 1 },
  ],
  doorverwijzing_vereist: true,
};

export const SPECIALITIES = [
  GENERAL_PRACTICIONER,
  {
    naam: "Cardiologie",
    beschrijving: "Specialist voor hart- en vaatziekten.",
    symptoms: [
      { name: "Pijn op de borst", urgency: 2 },
      { name: "Benauwdheid", urgency: 2 },
      { name: "Hartkloppingen", urgency: 2 },
      { name: "Duizeligheid of flauwvallen", urgency: 2 },
      { name: "Opgezwollen benen/enkels", urgency: 1 },
      { name: "Hoge bloeddruk", urgency: 2 },
      { name: "Onregelmatige hartslag", urgency: 2 },
      { name: "Pijn in arm, kaak of rug (uitstralend)", urgency: 2 },
      { name: "Plotselinge, hevige pijn op de borst", urgency: 3 },
      { name: "Ernstige benauwdheid", urgency: 3 },
      { name: "Pijn die uitstraalt naar arm, kaak of rug", urgency: 3 },
    ],
  },
  {
    naam: "Vaatheelkunde",
    beschrijving: "Specialist voor bloedvaten en doorbloedingsstoornissen.",
    symptoms: [
      { name: "Pijn in benen bij lopen (etalagebenen)", urgency: 2 },
      { name: "Niet-genezende wonden aan voeten/benen", urgency: 2 },
      { name: "Spataders", urgency: 1 },
      { name: "Koude of gevoelloze ledematen", urgency: 2 },
    ],
  },
  {
    naam: "Longgeneeskunde (Pulmonologie)",
    beschrijving: "Specialist voor longen en ademhalingsproblemen.",
    symptoms: [
      { name: "Chronische hoest", urgency: 2 },
      { name: "Piepende ademhaling", urgency: 2 },
      { name: "Benauwdheid", urgency: 2 },
      { name: "Bloed ophoesten", urgency: 3 },
      { name: "Aanhoudende congestie op de borst", urgency: 2 },
      { name: "Astma", urgency: 2 },
      { name: "COPD", urgency: 2 },
      { name: "Ernstige benauwdheid", urgency: 3 },
      { name: "Blauwe lippen/vingers (cyanose)", urgency: 3 },
    ],
  },
  {
    naam: "Neurologie",
    beschrijving: "Specialist voor zenuwstelsel en hersenen.",
    symptoms: [
      { name: "Hevige of plotselinge hoofdpijn", urgency: 2 },
      { name: "Toevallen (epilepsie)", urgency: 3 },
      { name: "Tintelingen of gevoelloosheid", urgency: 2 },
      { name: "Spierzwakte aan één kant van het lichaam", urgency: 3 },
      { name: "Onduidelijke spraak", urgency: 3 },
      { name: "Geheugenverlies", urgency: 2 },
      { name: "Verwardheid", urgency: 2 },
      { name: "Trillingen (tremor)", urgency: 1 },
      {
        name: "Plotselinge verlamming of zwakte (mogelijk beroerte)",
        urgency: 3,
      },
      { name: "Hevige hoofdpijn ('ergste van mijn leven')", urgency: 3 },
      { name: "Bewustzijnsverlies", urgency: 3 },
    ],
  },
  {
    naam: "Psychiatrie",
    beschrijving: "Specialist voor geestelijke gezondheid.",
    symptoms: [
      { name: "Aanhoudende verdriet", urgency: 2 },
      { name: "Angststoornissen", urgency: 2 },
      { name: "Stemmingswisselingen", urgency: 1 },
      { name: "Suïcidale gedachten", urgency: 3 },
      { name: "Hallucinaties", urgency: 3 },
      { name: "Slaapproblemen", urgency: 1 },
      { name: "Onverklaarde paniekaanvallen", urgency: 2 },
      { name: "Psychose (hallucinaties/wanen)", urgency: 3 },
    ],
  },
  {
    naam: "Orthopedie",
    beschrijving: "Specialist voor botten, gewrichten en spieren.",
    symptoms: [
      { name: "Gewrichtspijn (knieën, heupen, schouders)", urgency: 1 },
      { name: "Botpijn", urgency: 2 },
      { name: "Breuken", urgency: 3 },
      { name: "Beperkte beweeglijkheid", urgency: 2 },
      { name: "Rugpijn (chronisch of na blessure)", urgency: 1 },
      { name: "Hevige pijn na val/blessure", urgency: 3 },
      { name: "Onvermogen om een ledemaat te bewegen", urgency: 3 },
      { name: "Zichtbare vervorming", urgency: 3 },
    ],
  },
  {
    naam: "Reumatologie",
    beschrijving:
      "Specialist voor reumatische aandoeningen en auto-immuunziekten.",
    symptoms: [
      { name: "Opgezwollen/gevoelige gewrichten", urgency: 2 },
      { name: "Chronische spierpijn", urgency: 2 },
      { name: "Onverklaarde huiduitslag met gewrichtspijn", urgency: 2 },
      {
        name: "Stijfheid in gewrichten (o.a. reumatoïde artritis, lupus)",
        urgency: 2,
      },
    ],
  },
  {
    naam: "Maag-Darm-Levergeneeskunde (Gastro-enterologie)",
    beschrijving: "Specialist voor spijsverteringsstelsel.",
    symptoms: [
      { name: "Buikpijn", urgency: 1 },
      { name: "Opgeblazen gevoel", urgency: 1 },
      { name: "Diarree of obstipatie", urgency: 1 },
      { name: "Bloed in ontlasting", urgency: 3 },
      { name: "Braken met bloed", urgency: 3 },
      { name: "Brandend maagzuur", urgency: 1 },
      { name: "Moeilijk slikken", urgency: 2 },
      { name: "Hevige buikpijn", urgency: 3 },
      {
        name: "Zwarte/teerachtige ontlasting (mogelijke inwendige bloeding)",
        urgency: 3,
      },
    ],
  },
  {
    naam: "Hepatologie",
    beschrijving: "Specialist voor leveraandoeningen.",
    symptoms: [
      { name: "Geelzucht (gele huid/ogen)", urgency: 2 },
      { name: "Donkere urine", urgency: 2 },
      { name: "Lichte ontlasting", urgency: 1 },
      { name: "Opgezwollen buik", urgency: 2 },
      { name: "Chronische vermoeidheid", urgency: 1 },
      { name: "Onverklaarde blauwe plekken", urgency: 2 },
    ],
  },
  {
    naam: "Urologie",
    beschrijving: "Specialist voor urinewegen en mannelijke geslachtsorganen.",
    symptoms: [
      { name: "Bloed in urine", urgency: 3 },
      { name: "Veelvuldig plassen", urgency: 1 },
      { name: "Pijn bij plassen", urgency: 2 },
      { name: "Nierstenen", urgency: 2 },
      { name: "Erectiestoornissen", urgency: 1 },
      { name: "Prostaatproblemen", urgency: 2 },
      { name: "Pijn of zwelling in teelballen", urgency: 2 },
      { name: "Plotselinge, hevige rugpijn (nierstenen)", urgency: 3 },
      { name: "Onvermogen om te plassen", urgency: 3 },
      {
        name: "Testiculaire torsie (plotselinge hevige pijn in teelbal)",
        urgency: 3,
      },
    ],
  },
  {
    naam: "Gynaecologie",
    beschrijving: "Specialist voor vrouwengezondheid en voortplanting.",
    symptoms: [
      { name: "Abnormaal vaginaal bloedverlies", urgency: 2 },
      { name: "Pijn in onderbuik", urgency: 2 },
      { name: "Onregelmatige menstruatie", urgency: 1 },
      { name: "Afscheiding of jeuk in vagina", urgency: 1 },
      { name: "Overgangsklachten", urgency: 1 },
      { name: "Onvruchtbaarheid", urgency: 2 },
      { name: "Hevige onderbuikpijn", urgency: 3 },
      { name: "Hevig bloedverlies met duizeligheid", urgency: 3 },
      {
        name: "Verminderde foetale bewegingen tijdens zwangerschap",
        urgency: 3,
      },
    ],
  },
  {
    naam: "Verloskunde",
    beschrijving: "Specialist voor zwangerschap en bevalling.",
    symptoms: [
      { name: "Zwangerschapsgerelateerde klachten", urgency: 1 },
      { name: "Weeën", urgency: 2 },
      { name: "Verminderde foetale bewegingen", urgency: 3 },
      { name: "Vaginale bloedingen tijdens zwangerschap", urgency: 3 },
      { name: "Hevige buikpijn tijdens zwangerschap", urgency: 3 },
    ],
  },
  {
    naam: "Endocrinologie",
    beschrijving: "Specialist voor hormonen en stofwisseling.",
    symptoms: [
      { name: "Onverklaarbaar gewichtsverlies of -toename", urgency: 2 },
      { name: "Extreme dorst en veel plassen (diabetes)", urgency: 2 },
      { name: "Vermoeidheid", urgency: 1 },
      { name: "Warmte/koude-intolerantie", urgency: 1 },
      { name: "Opgezwollen schildklier", urgency: 2 },
      { name: "Haaruitval", urgency: 1 },
    ],
  },
  {
    naam: "Hematologie",
    beschrijving: "Specialist voor bloedziekten.",
    symptoms: [
      { name: "Onverklaarde blauwe plekken of bloedingen", urgency: 2 },
      { name: "Frequente infecties", urgency: 2 },
      { name: "Bleke huid (anemie)", urgency: 2 },
      { name: "Opgezwollen lymfeklieren", urgency: 2 },
      { name: "Nachttranspiratie", urgency: 1 },
    ],
  },
  {
    naam: "Keel-, Neus- en Oorheelkunde (KNO)",
    beschrijving: "Specialist voor oren, neus en keel.",
    symptoms: [
      { name: "Gehoorverlies", urgency: 2 },
      { name: "Oorpijn of afscheiding", urgency: 2 },
      { name: "Oorsuizen (tinnitus)", urgency: 1 },
      { name: "Chronische bijholteontsteking", urgency: 2 },
      { name: "Keelpijn", urgency: 1 },
      { name: "Hesheid", urgency: 1 },
      { name: "Duizeligheid (vertigo)", urgency: 2 },
      { name: "Plotseling gehoorverlies", urgency: 3 },
      { name: "Ernstige duizeligheid met braken", urgency: 3 },
    ],
  },
  {
    naam: "Oogheelkunde",
    beschrijving: "Specialist voor ogen.",
    symptoms: [
      { name: "Wazig zicht", urgency: 2 },
      { name: "Oogpijn", urgency: 2 },
      { name: "Roodheid of zwelling van het oog", urgency: 2 },
      {
        name: "Lichtflitsen of vlekjes (vliegjes) in het gezichtsveld",
        urgency: 2,
      },
      { name: "Plotseling gezichtsverlies", urgency: 3 },
      { name: "Droge of jeukende ogen", urgency: 1 },
      { name: "Oogletsel", urgency: 3 },
      { name: "Chemische blootstelling", urgency: 3 },
    ],
  },
  {
    naam: "Dermatologie",
    beschrijving: "Specialist voor huid, haar en nagels.",
    symptoms: [
      { name: "Huiduitslag", urgency: 1 },
      { name: "Moedervlekken of veranderingen in huidafwijkingen", urgency: 2 },
      { name: "Jeuk", urgency: 1 },
      { name: "Haaruitval", urgency: 1 },
      { name: "Nagelafwijkingen", urgency: 1 },
      { name: "Ernstige acne", urgency: 1 },
      { name: "Huidinfecties", urgency: 2 },
      { name: "Snel uitbreidende uitslag", urgency: 3 },
      { name: "Ernstige brandwonden", urgency: 3 },
      { name: "Teken van huidinfectie (rode strepen, pus)", urgency: 3 },
    ],
  },
  {
    naam: "Spoedeisende Hulp (SEH)",
    beschrijving: "Voor levensbedreigende situaties.",
    symptoms: [
      {
        name: "Pijn op de borst of benauwdheid (mogelijk hartaanval)",
        urgency: 3,
      },
      {
        name: "Ernstige allergische reacties (ademhalingsproblemen, zwelling van gezicht/keel)",
        urgency: 3,
      },
      {
        name: "Beroerte-verschijnselen (plotselinge verlamming, spraakstoornis, gezichtsverlies)",
        urgency: 3,
      },
      {
        name: "Ernstige trauma's (hoofdletsel, diepe snijwonden, botbreuken)",
        urgency: 3,
      },
      { name: "Vergiftiging of overdosering", urgency: 3 },
      {
        name: "Hoge koorts met verwardheid (mogelijk hersenvliesontsteking)",
        urgency: 3,
      },
      {
        name: "Ernstige uitdroging (geen urineren in 12+ uur, verwardheid)",
        urgency: 3,
      },
    ],
  },
  {
    naam: "Infectieziekten",
    beschrijving: "Specialist voor besmettelijke ziekten.",
    symptoms: [
      { name: "Aanhoudende koorts", urgency: 2 },
      { name: "Onverklaarde infecties", urgency: 2 },
      { name: "Reisgerelateerde ziekten (malaria, dengue)", urgency: 2 },
      { name: "HIV/AIDS", urgency: 2 },
      {
        name: "Chronische vermoeidheid met opgezwollen lymfeklieren",
        urgency: 2,
      },
    ],
  },
  {
    naam: "Kindergeneeskunde (Pediatrie)",
    beschrijving: "Specialist voor gezondheid van kinderen.",
    symptoms: [
      { name: "Kindergeneeskundige aandoeningen", urgency: 1 },
      { name: "Ontwikkelingsstoornissen", urgency: 2 },
      { name: "Koorts bij baby's", urgency: 2 },
      { name: "Vaccinatievragen", urgency: 1 },
      { name: "Groei- of voedingsproblemen", urgency: 2 },
      { name: "Hoge koorts bij baby's <3 maanden", urgency: 3 },
      { name: "Ademhalingsproblemen", urgency: 3 },
      { name: "Toevallen", urgency: 3 },
      { name: "Uitdroging (geen natte luiers in 6+ uur)", urgency: 3 },
    ],
  },
  {
    naam: "Ouderengeneeskunde (Geriatrie)",
    beschrijving: "Specialist voor gezondheid van ouderen.",
    symptoms: [
      { name: "Geheugenverlies", urgency: 2 },
      { name: "Valincidenten", urgency: 2 },
      { name: "Beperkte mobiliteit", urgency: 1 },
      { name: "Chronische aandoeningen", urgency: 2 },
      { name: "Medicatiemanagement", urgency: 1 },
      { name: "Fragiliteit", urgency: 1 },
    ],
  },
  {
    naam: "Oncologie",
    beschrijving: "Specialist voor kanker.",
    symptoms: [
      { name: "Onverklaarde knobels of zwellingen", urgency: 2 },
      { name: "Aanhoudende pijn", urgency: 2 },
      { name: "Onverklaarbaar gewichtsverlies", urgency: 2 },
      { name: "Veranderingen in moedervlekken", urgency: 2 },
      { name: "Chronische hoest met bloed", urgency: 3 },
      { name: "Moeilijk slikken", urgency: 2 },
    ],
  },
  {
    naam: "Allergologie en Immunologie",
    beschrijving: "Specialist voor allergieën en immuunstoornissen.",
    symptoms: [
      { name: "Allergische reacties (galbulten, zwellingen)", urgency: 2 },
      { name: "Astma", urgency: 2 },
      { name: "Voedsel- of medicijnallergieën", urgency: 2 },
      { name: "Frequente infecties", urgency: 2 },
      { name: "Immuunstoornissen", urgency: 2 },
      { name: "Ernstige allergische reactie (anafylaxie)", urgency: 3 },
    ],
  },
  {
    naam: "Revalidatiegeneeskunde",
    beschrijving: "Specialist voor herstel en revalidatie.",
    symptoms: [
      { name: "Chronische pijn", urgency: 2 },
      { name: "Invaliditeit", urgency: 2 },
      { name: "Herstel na letsel of operatie", urgency: 1 },
      { name: "Revalidatie na beroerte", urgency: 2 },
      { name: "Ruggenmergletsel", urgency: 2 },
    ],
  },
];
