export const GENERAL_PRACTICIONER = {
  naam: "Huisarts (Algemene Geneeskunde)",
  beschrijving:
    "Eerste aanspreekpunt voor algemene klachten, doorverwijzingen en preventieve zorg.",
  symptomen: [
    "Koorts",
    "Vermoeidheid",
    "Algehele zwakte",
    "Onverklaarbaar gewichtsverlies",
    "Lichte pijn",
    "Hoest",
    "Verkoudheid",
    "Griepachtige klachten",
    "Kleine infecties",
  ],
  noodgeval: false,
  doorverwijzing_vereist: true,
};

export const SPECIALITIES = [
  GENERAL_PRACTICIONER,
  {
    naam: "Cardiologie",
    beschrijving: "Specialist voor hart- en vaatziekten.",
    symptomen: [
      "Pijn op de borst",
      "Benauwdheid",
      "Hartkloppingen",
      "Duizeligheid of flauwvallen",
      "Opgezwollen benen/enkels",
      "Hoge bloeddruk",
      "Onregelmatige hartslag",
      "Pijn in arm, kaak of rug (uitstralend)",
    ],
    noodgeval: true,
    noodgeval_symptomen: [
      "Plotselinge, hevige pijn op de borst",
      "Ernstige benauwdheid",
      "Pijn die uitstraalt naar arm, kaak of rug",
    ],
  },
  {
    naam: "Vaatheelkunde",
    beschrijving: "Specialist voor bloedvaten en doorbloedingsstoornissen.",
    symptomen: [
      "Pijn in benen bij lopen (etalagebenen)",
      "Niet-genezende wonden aan voeten/benen",
      "Spataders",
      "Koude of gevoelloze ledematen",
    ],
    noodgeval: false,
  },
  {
    naam: "Longgeneeskunde (Pulmonologie)",
    beschrijving: "Specialist voor longen en ademhalingsproblemen.",
    symptomen: [
      "Chronische hoest",
      "Piepende ademhaling",
      "Benauwdheid",
      "Bloed ophoesten",
      "Aanhoudende congestie op de borst",
      "Astma",
      "COPD",
    ],
    noodgeval: true,
    noodgeval_symptomen: [
      "Ernstige benauwdheid",
      "Blauwe lippen/vingers (cyanose)",
    ],
  },
  {
    naam: "Neurologie",
    beschrijving: "Specialist voor zenuwstelsel en hersenen.",
    symptomen: [
      "Hevige of plotselinge hoofdpijn",
      "Toevallen (epilepsie)",
      "Tintelingen of gevoelloosheid",
      "Spierzwakte aan één kant van het lichaam",
      "Onduidelijke spraak",
      "Geheugenverlies",
      "Verwardheid",
      "Trillingen (tremor)",
    ],
    noodgeval: true,
    noodgeval_symptomen: [
      "Plotselinge verlamming of zwakte (mogelijk beroerte)",
      "Hevige hoofdpijn ('ergste van mijn leven')",
      "Bewustzijnsverlies",
    ],
  },
  {
    naam: "Psychiatrie",
    beschrijving: "Specialist voor geestelijke gezondheid.",
    symptomen: [
      "Aanhoudende verdriet",
      "Angststoornissen",
      "Stemmingswisselingen",
      "Suïcidale gedachten",
      "Hallucinaties",
      "Slaapproblemen",
      "Onverklaarde paniekaanvallen",
    ],
    noodgeval: true,
    noodgeval_symptomen: [
      "Suïcidale gedachten of zelfmoordpoging",
      "Psychose (hallucinaties/wanen)",
    ],
  },
  {
    naam: "Orthopedie",
    beschrijving: "Specialist voor botten, gewrichten en spieren.",
    symptomen: [
      "Gewrichtspijn (knieën, heupen, schouders)",
      "Botpijn",
      "Breuken",
      "Beperkte beweeglijkheid",
      "Rugpijn (chronisch of na blessure)",
    ],
    noodgeval: true,
    noodgeval_symptomen: [
      "Hevige pijn na val/blessure",
      "Onvermogen om een ledemaat te bewegen",
      "Zichtbare vervorming",
    ],
  },
  {
    naam: "Reumatologie",
    beschrijving:
      "Specialist voor reumatische aandoeningen en auto-immuunziekten.",
    symptomen: [
      "Opgezwollen/gevoelige gewrichten",
      "Chronische spierpijn",
      "Onverklaarde huiduitslag met gewrichtspijn",
      "Stijfheid in gewrichten (o.a. reumatoïde artritis, lupus)",
    ],
    noodgeval: false,
  },
  {
    naam: "Maag-Darm-Levergeneeskunde (Gastro-enterologie)",
    beschrijving: "Specialist voor spijsverteringsstelsel.",
    symptomen: [
      "Buikpijn",
      "Opgeblazen gevoel",
      "Diarree of obstipatie",
      "Bloed in ontlasting",
      "Braken met bloed",
      "Brandend maagzuur",
      "Moeilijk slikken",
    ],
    noodgeval: true,
    noodgeval_symptomen: [
      "Hevige buikpijn",
      "Braken met bloed",
      "Zwarte/teerachtige ontlasting (mogelijke inwendige bloeding)",
    ],
  },
  {
    naam: "Hepatologie",
    beschrijving: "Specialist voor leveraandoeningen.",
    symptomen: [
      "Geelzucht (gele huid/ogen)",
      "Donkere urine",
      "Lichte ontlasting",
      "Opgezwollen buik",
      "Chronische vermoeidheid",
      "Onverklaarde blauwe plekken",
    ],
    noodgeval: false,
  },
  {
    naam: "Urologie",
    beschrijving: "Specialist voor urinewegen en mannelijke geslachtsorganen.",
    symptomen: [
      "Bloed in urine",
      "Veelvuldig plassen",
      "Pijn bij plassen",
      "Nierstenen",
      "Erectiestoornissen",
      "Prostaatproblemen",
      "Pijn of zwelling in teelballen",
    ],
    noodgeval: true,
    noodgeval_symptomen: [
      "Plotselinge, hevige rugpijn (nierstenen)",
      "Onvermogen om te plassen",
      "Testiculaire torsie (plotselinge hevige pijn in teelbal)",
    ],
  },
  {
    naam: "Gynaecologie",
    beschrijving: "Specialist voor vrouwengezondheid en voortplanting.",
    symptomen: [
      "Abnormaal vaginaal bloedverlies",
      "Pijn in onderbuik",
      "Onregelmatige menstruatie",
      "Afscheiding of jeuk in vagina",
      "Overgangsklachten",
      "Onvruchtbaarheid",
    ],
    noodgeval: true,
    noodgeval_symptomen: [
      "Hevige onderbuikpijn",
      "Hevig bloedverlies met duizeligheid",
      "Verminderde foetale bewegingen tijdens zwangerschap",
    ],
  },
  {
    naam: "Verloskunde",
    beschrijving: "Specialist voor zwangerschap en bevalling.",
    symptomen: [
      "Zwangerschapsgerelateerde klachten",
      "Weeën",
      "Verminderde foetale bewegingen",
      "Vaginale bloedingen tijdens zwangerschap",
    ],
    noodgeval: true,
    noodgeval_symptomen: [
      "Vaginale bloedingen tijdens zwangerschap",
      "Hevige buikpijn tijdens zwangerschap",
    ],
  },
  {
    naam: "Endocrinologie",
    beschrijving: "Specialist voor hormonen en stofwisseling.",
    symptomen: [
      "Onverklaarbaar gewichtsverlies of -toename",
      "Extreme dorst en veel plassen (diabetes)",
      "Vermoeidheid",
      "Warmte/koude-intolerantie",
      "Opgezwollen schildklier",
      "Haaruitval",
    ],
    noodgeval: false,
  },
  {
    naam: "Hematologie",
    beschrijving: "Specialist voor bloedziekten.",
    symptomen: [
      "Onverklaarde blauwe plekken of bloedingen",
      "Frequente infecties",
      "Bleke huid (anemie)",
      "Opgezwollen lymfeklieren",
      "Nachttranspiratie",
    ],
    noodgeval: false,
  },
  {
    naam: "Keel-, Neus- en Oorheelkunde (KNO)",
    beschrijving: "Specialist voor oren, neus en keel.",
    symptomen: [
      "Gehoorverlies",
      "Oorpijn of afscheiding",
      "Oorsuizen (tinnitus)",
      "Chronische bijholteontsteking",
      "Keelpijn",
      "Hesheid",
      "Duizeligheid (vertigo)",
    ],
    noodgeval: true,
    noodgeval_symptomen: [
      "Plotseling gehoorverlies",
      "Ernstige duizeligheid met braken",
    ],
  },
  {
    naam: "Oogheelkunde",
    beschrijving: "Specialist voor ogen.",
    symptomen: [
      "Wazig zicht",
      "Oogpijn",
      "Roodheid of zwelling van het oog",
      "Lichtflitsen of vlekjes (vliegjes) in het gezichtsveld",
      "Plotseling gezichtsverlies",
      "Droge of jeukende ogen",
    ],
    noodgeval: true,
    noodgeval_symptomen: [
      "Plotseling gezichtsverlies",
      "Oogletsel",
      "Chemische blootstelling",
    ],
  },
  {
    naam: "Dermatologie",
    beschrijving: "Specialist voor huid, haar en nagels.",
    symptomen: [
      "Huiduitslag",
      "Moedervlekken of veranderingen in huidafwijkingen",
      "Jeuk",
      "Haaruitval",
      "Nagelafwijkingen",
      "Ernstige acne",
      "Huidinfecties",
    ],
    noodgeval: false,
    noodgeval_symptomen: [
      "Snel uitbreidende uitslag",
      "Ernstige brandwonden",
      "Teken van huidinfectie (rode strepen, pus)",
    ],
  },
  {
    naam: "Spoedeisende Hulp (SEH)",
    beschrijving: "Voor levensbedreigende situaties.",
    symptomen: [
      "Pijn op de borst of benauwdheid (mogelijk hartaanval)",
      "Ernstige allergische reacties (ademhalingsproblemen, zwelling van gezicht/keel)",
      "Beroerte-verschijnselen (plotselinge verlamming, spraakstoornis, gezichtsverlies)",
      "Ernstige trauma's (hoofdletsel, diepe snijwonden, botbreuken)",
      "Vergiftiging of overdosering",
      "Hoge koorts met verwardheid (mogelijk hersenvliesontsteking)",
      "Ernstige uitdroging (geen urineren in 12+ uur, verwardheid)",
    ],
    noodgeval: true,
  },
  {
    naam: "Infectieziekten",
    beschrijving: "Specialist voor besmettelijke ziekten.",
    symptomen: [
      "Aanhoudende koorts",
      "Onverklaarde infecties",
      "Reisgerelateerde ziekten (malaria, dengue)",
      "HIV/AIDS",
      "Chronische vermoeidheid met opgezwollen lymfeklieren",
    ],
    noodgeval: false,
  },
  {
    naam: "Kindergeneeskunde (Pediatrie)",
    beschrijving: "Specialist voor gezondheid van kinderen.",
    symptomen: [
      "Kindergeneeskundige aandoeningen",
      "Ontwikkelingsstoornissen",
      "Koorts bij baby's",
      "Vaccinatievragen",
      "Groei- of voedingsproblemen",
    ],
    noodgeval: true,
    noodgeval_symptomen: [
      "Hoge koorts bij baby's <3 maanden",
      "Ademhalingsproblemen",
      "Toevallen",
      "Uitdroging (geen natte luiers in 6+ uur)",
    ],
  },
  {
    naam: "Ouderengeneeskunde (Geriatrie)",
    beschrijving: "Specialist voor gezondheid van ouderen.",
    symptomen: [
      "Geheugenverlies",
      "Valincidenten",
      "Beperkte mobiliteit",
      "Chronische aandoeningen",
      "Medicatiemanagement",
      "Fragiliteit",
    ],
    noodgeval: false,
  },
  {
    naam: "Oncologie",
    beschrijving: "Specialist voor kanker.",
    symptomen: [
      "Onverklaarde knobels of zwellingen",
      "Aanhoudende pijn",
      "Onverklaarbaar gewichtsverlies",
      "Veranderingen in moedervlekken",
      "Chronische hoest met bloed",
      "Moeilijk slikken",
    ],
    noodgeval: false,
  },
  {
    naam: "Allergologie en Immunologie",
    beschrijving: "Specialist voor allergieën en immuunstoornissen.",
    symptomen: [
      "Allergische reacties (galbulten, zwellingen)",
      "Astma",
      "Voedsel- of medicijnallergieën",
      "Frequente infecties",
      "Immuunstoornissen",
    ],
    noodgeval: true,
    noodgeval_symptomen: ["Ernstige allergische reactie (anafylaxie)"],
  },
  {
    naam: "Revalidatiegeneeskunde",
    beschrijving: "Specialist voor herstel en revalidatie.",
    symptomen: [
      "Chronische pijn",
      "Invaliditeit",
      "Herstel na letsel of operatie",
      "Revalidatie na beroerte",
      "Ruggenmergletsel",
    ],
    noodgeval: false,
  },
];
