export const symptomOptions: string[] = [
  "Gordelroos",
  "Hoesten",
  "Keelpijn",
  "Diarree",
  "Oorpijn",
  "Koorts",
  "Blaasontsteking",
  "Hoofdpijn",
  "Hersenschudding",
  "Eczeem",
  "Waterpokken",
  "Buikpijn",
  "Griep",
  "Rugpijn",
  "Keelontsteking",
  "Duizeligheid",
];